# Generated by Django 4.1.3 on 2022-12-06 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotterapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='body_section',
        ),
    ]
