# Generated by Django 4.1.3 on 2023-01-09 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotterapi', '0002_remove_exercise_body_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='active',
        ),
    ]
