# Generated by Django 4.1.3 on 2023-01-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotterapi', '0004_profile_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='days_of_week',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
